"""Default threshold definitions generated from Excel file"""

def get_default_thresholds():
    """Returns list of default threshold configurations"""
    return [
        {
            'id': 'threshold_Csjy7O1v',
            'category': 'Fuel Sensor',
            'parameter': 'fuel_level',
            'condition': '<=',
            'value': 10.0,
            'unit': 'cm',
            'severity': 'critical',
            'description': 'Fuel Low',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_3aTkNf2v',
            'category': 'Fuel Sensor',
            'parameter': 'fuel_level',
            'condition': '>=',
            'value': 10.0,
            'unit': 'L',
            'severity': 'critical',
            'description': 'Fuel Drop',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_AiFRvfmT',
            'category': 'Fuel Sensor',
            'parameter': 'fuel_level',
            'condition': '>=',
            'value': 20.0,
            'unit': 'L',
            'severity': 'high',
            'description': 'Refuel',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_umqD7KFH',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Grid Available',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_OuSSrDoz',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Grid Not Available',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_fu0v6QYS',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Grid  Low  Phase Voltage',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_oFtBzYrQ',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Grid Available and on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_adYD9W9X',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Grid Available and on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_HiP9EXjx',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Grid Available But Not on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_xCkoGq1E',
            'category': 'Grid ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Grid Available But Not on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_jSbwkGiH',
            'category': 'Grid ACEM',
            'parameter': 'frequency',
            'condition': '>=',
            'value': 55.0,
            'unit': 'Hz',
            'severity': 'high',
            'description': 'Grid High Frequency',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_6TiV7wEe',
            'category': 'Grid ACEM',
            'parameter': 'frequency',
            'condition': '<',
            'value': 45.0,
            'unit': 'Hz',
            'severity': 'critical',
            'description': 'Grid Low Frequency',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_SsrJX0RZ',
            'category': 'Battery',
            'parameter': 'battery_current',
            'condition': '>=',
            'value': -3.0,
            'unit': 'A',
            'severity': 'high',
            'description': 'Battery Discharge',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_QroPjdsf',
            'category': 'Battery',
            'parameter': 'battery_current',
            'condition': '>=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'high',
            'description': 'Battery Charge',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_zFTZy8VD',
            'category': 'Battery',
            'parameter': 'battery_current',
            'condition': '<=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Battery Floating',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_A3OvgwRO',
            'category': 'Battery',
            'parameter': 'battery_voltage',
            'condition': '<=',
            'value': 46.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Battery Low',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_ZHGBaULw',
            'category': 'Solar',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 5.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Solar On',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_34ovZ9NC',
            'category': 'Solar',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 5.0,
            'unit': 'A',
            'severity': 'critical',
            'description': 'Solar Off',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_TFf5gfQ3',
            'category': 'Gen ACEM',
            'parameter': 'unknown',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Gen On',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_X9pIGhx5',
            'category': 'Gen ACEM',
            'parameter': 'unknown',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Gen Off',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_IfeJFstd',
            'category': 'Gen ACEM',
            'parameter': 'voltage',
            'condition': '<',
            'value': 174.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Gen  Low  Phase Voltage',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_FgrrMjot',
            'category': 'Gen ACEM',
            'parameter': 'voltage',
            'condition': '>=',
            'value': 0.0,
            'unit': 'V',
            'severity': 'critical',
            'description': 'Gen  Low  Phase Voltage',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_T8YbcLgz',
            'category': 'Gen ACEM',
            'parameter': 'load_current',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Gen on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_GnoQpYli',
            'category': 'Gen ACEM',
            'parameter': 'load_current',
            'condition': '>=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Gen on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_lsO91Be8',
            'category': 'Gen ACEM',
            'parameter': 'load_current',
            'condition': '>=',
            'value': 174.0,
            'unit': 'V',
            'severity': 'info',
            'description': 'Gen On but Not on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_ZFaGxVXj',
            'category': 'Gen ACEM',
            'parameter': 'load_current',
            'condition': '>=',
            'value': 3.0,
            'unit': 'A',
            'severity': 'info',
            'description': 'Gen On but Not on Load',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_5hBJrxrE',
            'category': 'Gen ACEM',
            'parameter': 'frequency',
            'condition': '>',
            'value': 55.0,
            'unit': 'Hz',
            'severity': 'high',
            'description': 'Gen High Frequency',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_hZQbJFZa',
            'category': 'Gen ACEM',
            'parameter': 'frequency',
            'condition': '<',
            'value': 45.0,
            'unit': 'HZ',
            'severity': 'critical',
            'description': 'Gen Low Frequency',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_HC5wszGR',
            'category': 'Temperature Sensor',
            'parameter': 'temperature',
            'condition': '>',
            'value': 30.0,
            'unit': '°c',
            'severity': 'high',
            'description': 'High Temperature',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_T1uzUZHE',
            'category': 'Power Alarms',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'critical',
            'description': 'Site Down',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_CzcdoYVK',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_ZMjWfpzm',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_qd8BaZ25',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_llgkOp5z',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_kvsVOmLL',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_APNMgOio',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_foZ1qwDZ',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_dlhNrlN8',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_0md3TRgW',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_4Jc5hqlV',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_5Ti7Jz98',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_fWP8XIO5',
            'category': 'Power Status',
            'parameter': 'power',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_bGZl9iP5',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_GyuMFsnE',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_6RkXFFJz',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_HwCNeCbW',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Grid',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_MOXMH2PF',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_2IGFkNud',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_nA5o2OXS',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_iAc0a5Cv',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Battery',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_l1BPycs6',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_vS5r2D5J',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.0,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_q9yq4zKR',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_7yov1tZp',
            'category': 'Power Status',
            'parameter': 'solar_current',
            'condition': '>=',
            'value': 0.6,
            'unit': 'KW',
            'severity': 'info',
            'description': 'Site on Solar with Generator',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_s7r9W9z3',
            'category': 'Tenant',
            'parameter': 'tenant_consumption',
            'condition': '>=',
            'value': 50.0,
            'unit': '%',
            'severity': 'critical',
            'description': 'Tenant Down',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
        {
            'id': 'threshold_uAVSDvjQ',
            'category': 'Tenant',
            'parameter': 'load_current',
            'condition': '>=',
            'value': 115.0,
            'unit': '%',
            'severity': 'info',
            'description': 'Load Increase',
            'sites': '[]',
            'applies_to': 'all',
            'enabled': True,
            'trigger_count': 0,
            'last_triggered': None,
            'region_id': None,
            'cluster_id': None,
            'site_id': None,
            'location_name': None,
        },
    ]
